### ISSUE TITLE
字体加载失败?

### ISSUE THREAD

**Issue by forestlightelf** [oubenruing/svg-text-animate#12]
![image](https://user-images.githubusercontent.com/58362707/103472904-dc9f6480-4dcd-11eb-881e-79e28e42e90b.png)
<script>
代码如下，字体使用您提供的链接，vue框架.
[pastebin](https://paste.ubuntu.com/p/hNxJYDPdyf)

**Comment by oubenruing** [comment]
先调用setFont()方法加载字体之后，才能调用create()方法。注意setFont是异步方法。
