### ISSUE TITLE
Svg path animation 

### ISSUE THREAD

**Issue by yahya2018** [oubenruing/svg-text-animate#13]
Thanks for the great tool,
Is there any way to animate svg path ( after importing svg file) using your tool ?. For example, a math symbols or a picture with svg path.

Thanks in advance

**Comment by oubenruing** [comment]
Hi，
You can use a tool like [icomoon](https://icomoon.io/app/) to generate the svg into a font file, and you will get the unicode code of the characters (e.g. f581). Then use [svg-text-animate](https://github.com/oubenruing/svg-text-animate) to animate the font by the 'create' method like the code below.
`yourfonts.create(String.fromCharCode(0xf581), YOUR_DOM_SELECT)`

**Comment by yahya2018** [comment]
I really appreciate it.
Thanks
