### ISSUE TITLE
Clear existing SVG on redraw

### ISSUE THREAD

**Issue by garyanewsome** [oubenruing/svg-text-animate#2]
Thank you for the library.

I had it worked out, but it wasn't quite fitting my use case and reverted back to your code. If this is a feature you would like to pursue I would be happy to share what I was doing and/or even work on it with you.

**Comment by oubenruing** [comment]
Thanks for the issue .
When I want to clear a svg, I just clear the parent element of the svg directly and call the create method again. Can such an operation solve your problem?  Or can I learn more about the details of your needs?

**Comment by garyanewsome** [comment]
That does the trick beautifully. My apologies I didn't think of that sooner. Thanks again!

**Comment by oubenruing** [comment]
@garyanewsome ：I carefully considered your suggestion. So I edited the “create” method, it will clear the parent element before inserting SVG. And I added an "Add" method to insert SVG directly into the parent element.  If you have any other ideas, please let me know. Thank you!
