### ISSUE TITLE
fill

### ISSUE THREAD

**Issue by alexla** [oubenruing/svg-text-animate#21]
Hi,
you have an option for stroke-width. Is there an option for fill? All thicker fonts seem to be transparent on their fill and I wonder if there is an option to set the fill color.

Thanks

**Comment by oubenruing** [comment]
Not yet, but I will add it as soon as possible.

**Comment by oubenruing** [comment]
> Hi, you have an option for stroke-width. Is there an option for fill? All thicker fonts seem to be transparent on their fill and I wonder if there is an option to set the fill color.
> 
> Thanks

The "fill" option has been added in version 1.4.0 .You can update the dependencies and then give it a try.
